# Generated by Django 4.0.3 on 2022-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoename', models.CharField(max_length=200)),
                ('shoeimg', models.ImageField(blank=True, upload_to='')),
                ('Link', models.CharField(max_length=200)),
                ('Site', models.CharField(max_length=200)),
                ('nameentry', models.CharField(blank=True, default=None, max_length=200)),
                ('birthentry', models.CharField(blank=True, default=None, max_length=200)),
                ('phoneentry', models.CharField(blank=True, default=None, max_length=200)),
                ('nikeidentry', models.CharField(blank=True, default=None, max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('user_size', models.IntegerField(default=0)),
                ('user_birth', models.CharField(blank=True, default=0, max_length=200)),
                ('user_nikeid', models.CharField(blank=True, default='', max_length=200)),
                ('user_phonenumber', models.CharField(default='010', max_length=200)),
            ],
        ),
    ]
