# Generated by Django 4.0.3 on 2023-02-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_no', models.AutoField(db_column='member_no', primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_column='member_id', max_length=50)),
                ('member_pwd', models.CharField(db_column='member_pwd', max_length=50)),
                ('member_realname', models.CharField(db_column='member_realname', max_length=200)),
                ('member_email', models.CharField(db_column='member_email', max_length=255)),
                ('member_nickname', models.CharField(db_column='member_nickname', max_length=200)),
                ('member_birth', models.CharField(db_column='member_birth', max_length=200)),
                ('member_nikeid', models.CharField(db_column='member_nikeid', max_length=200)),
                ('member_phonenumber', models.CharField(db_column='member_phonenumber', max_length=200)),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
                ('register_date', models.DateTimeField(db_column='register_date')),
                ('is_active', models.BooleanField(db_column='is_active', default=False)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoename', models.CharField(max_length=200)),
                ('shoeengname', models.CharField(max_length=200)),
                ('shoebrand', models.CharField(max_length=200)),
                ('serialno', models.CharField(default=None, max_length=50, unique=True)),
                ('pubdate', models.CharField(max_length=200)),
                ('shoeprice', models.CharField(max_length=200)),
                ('shoedetail', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Shoeimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(default=None, max_length=50)),
                ('shoeimg', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoesite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(default=None, max_length=50)),
                ('sitename', models.CharField(max_length=200)),
                ('nameentry', models.CharField(blank=True, max_length=200, null=True)),
                ('birthentry', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneentry', models.CharField(blank=True, max_length=200, null=True)),
                ('nikeidentry', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='date end')),
                ('sitelink', models.CharField(max_length=200)),
                ('shoesiteunique', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoesiteimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
