# Generated by Django 4.0.3 on 2022-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeimg',
            name='shoeimg',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
