# Generated by Django 4.0.3 on 2023-04-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(db_column='comment', max_length=200)),
                ('created_date', models.DateTimeField(db_column='register_date')),
                ('approved_comment', models.BooleanField(db_column='approved_comment', default=False)),
                ('member_nickname', models.ForeignKey(db_column='member_nickname', on_delete=django.db.models.deletion.CASCADE, to='draw.member')),
                ('serialno', models.ForeignKey(db_column='serialno', on_delete=django.db.models.deletion.CASCADE, to='draw.shoe')),
            ],
        ),
    ]
