# Generated by Django 4.0.3 on 2023-06-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(db_column='serialno', max_length=200)),
                ('member_nickname', models.CharField(db_column='member_nickname', max_length=20)),
                ('comment', models.CharField(db_column='comment', max_length=200)),
                ('created_date', models.DateTimeField(db_column='created_date')),
                ('approved_comment', models.BooleanField(db_column='approved_comment', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shoeimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(default=None, max_length=50)),
                ('shoeimg', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoesite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(default=None, max_length=50)),
                ('sitename', models.CharField(max_length=200)),
                ('nameentry', models.CharField(blank=True, max_length=200, null=True)),
                ('birthentry', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneentry', models.CharField(blank=True, max_length=200, null=True)),
                ('nikeidentry', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='date end')),
                ('sitelink', models.CharField(max_length=200)),
                ('shoesiteunique', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoesiteimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoename', models.CharField(max_length=200)),
                ('shoeengname', models.CharField(max_length=200)),
                ('shoebrand', models.CharField(max_length=200)),
                ('serialno', models.CharField(default=None, max_length=50, unique=True)),
                ('pubdate', models.CharField(max_length=200)),
                ('shoeprice', models.CharField(max_length=200)),
                ('shoedetail', models.TextField(default='-')),
                ('shoelikecount', models.IntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='liked_posts', to='draw.member')),
            ],
        ),
    ]
