# Generated by Django 4.0.3 on 2023-04-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='member_nickname',
            field=models.CharField(db_column='member_nickname', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='serialno',
            field=models.CharField(db_column='serialno', max_length=200),
        ),
    ]
