# Generated by Django 4.1.1 on 2022-10-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_alter_shoesite_birthentry_alter_shoesite_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeimg',
            name='serialno',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='shoesite',
            name='serialno',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
