# Generated by Django 4.0.3 on 2022-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_alter_userdata_usernickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userrealname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
