# Generated by Django 4.0.3 on 2023-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_searchterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_column='member_id', max_length=50)),
                ('code', models.CharField(max_length=6)),
                ('expiry_time', models.DateTimeField()),
            ],
        ),
    ]
