# Generated by Django 4.0.3 on 2022-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_userdata_userrealname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_no', models.AutoField(db_column='member_no', primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_column='member_id', max_length=50)),
                ('member_pwd', models.CharField(db_column='member_pwd', max_length=50)),
                ('member_realname', models.CharField(db_column='member_realname', max_length=200)),
                ('member_email', models.CharField(db_column='member_email', max_length=255)),
                ('member_nickname', models.CharField(db_column='member_nickname', max_length=200)),
                ('member_birth', models.CharField(db_column='member_birth', max_length=200)),
                ('member_nikeid', models.CharField(db_column='member_nikeid', max_length=200)),
                ('member_phonenumber', models.CharField(db_column='member_phonenumber', max_length=200)),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
                ('register_date', models.DateTimeField(db_column='register_date')),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
