# Generated by Django 4.0.3 on 2023-04-29 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draw', '0004_alter_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='likes_user',
            field=models.ManyToManyField(blank=True, related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
