# Generated by Django 4.0.3 on 2023-10-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesite',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
