# Generated by Django 4.0.3 on 2022-09-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_member_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoeimg',
            field=models.CharField(max_length=1000),
        ),
    ]
