# Generated by Django 4.0.3 on 2023-05-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_shoe_likes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(db_column='serialno', max_length=200)),
                ('member_no', models.CharField(db_column='member_no', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='likes_user',
        ),
    ]
