# Generated by Django 4.0.3 on 2023-05-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_shoe_shoelikecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoelikecount',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoelikeuser',
            field=models.ManyToManyField(to='draw.member'),
        ),
    ]
