# Generated by Django 4.0.3 on 2023-11-02 17:25

from django.db import migrations, models
import draw.models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_banner_avifimage_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bannerimg/', validators=[draw.models.validate_image_extension]),
        ),
    ]
