# Generated by Django 4.0.3 on 2023-05-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0008_remove_shoe_shoelikecount_shoe_shoelikeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='serialno',
            field=models.CharField(max_length=50),
        ),
    ]
