# Generated by Django 4.0.3 on 2023-05-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_alter_shoe_serialno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoelikeuser',
        ),
    ]
