# Generated by Django 4.0.3 on 2023-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_alter_banner_avifimage_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='product_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
