# Generated by Django 4.0.3 on 2023-11-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_shoe_product_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.BooleanField(default=False)),
                ('difficult', models.BooleanField(default=False)),
                ('comfortable', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('bug', models.BooleanField(default=False)),
                ('feedback', models.BooleanField(default=False)),
                ('others', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
