# Generated by Django 4.0.3 on 2023-05-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_remove_shoe_shoelikeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='shoelikeuser',
            field=models.ManyToManyField(to='draw.member'),
        ),
    ]
