# Generated by Django 4.0.3 on 2023-05-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0011_shoe_shoelikeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoelikeuser',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoelikecount',
            field=models.IntegerField(default=0),
        ),
    ]
