# Generated by Django 4.1.3 on 2023-12-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0012_rating'),
        ('draw', '0012_shoe_category_shoe_kream_number_shoe_product_color_and_more'),
    ]

    operations = [
    ]
