# Generated by Django 4.0.3 on 2023-05-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0012_remove_shoe_shoelikeuser_shoe_shoelikecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='serialno',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
