# Generated by Django 4.0.3 on 2023-05-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0013_alter_shoe_serialno'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='draw.member'),
        ),
    ]
